CREATE TABLE accounts (
    id VARCHAR(26) NOT NULL PRIMARY KEY,
    user_id VARCHAR(50) NOT NULL UNIQUE,
    version BIGINT NOT NULL DEFAULT 0,
    balance NUMERIC(10, 2) NOT NULL DEFAULT 0.00,
    status VARCHAR(20) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    closed_at TIMESTAMP WITH TIME ZONE
);