CREATE TABLE pix_keys (
    id VARCHAR(26) NOT NULL PRIMARY KEY,
    type VARCHAR(10) NOT NULL,
    version BIGINT NOT NULL DEFAULT 0,
    key_value VARCHAR(255) NOT NULL UNIQUE,
    account_id VARCHAR(26) NOT NULL,
    status VARCHAR(10) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    deleted_at TIMESTAMP WITH TIME ZONE
);