{
 "title": "Database dashboard",
 "time": { "from": "2026-02-28T11:41:26.215Z", "to": "2026-02-28T23:41:26.215Z" },
 "refresh": "5s",
 "panels": [
  {
   "title": "PostgreSQL - Top 10 Tables by Size",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "topk(10, sum by (postgresql_table_name) (postgresql_table_size_bytes))",
     "legendFormat": "{{postgresql_table_name}}"
    }
   ]
  },
  {
   "title": "PostgreSQL - Disk Blocks Read (per second)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(postgresql_blocks_read_total[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "PostgreSQL - Database Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "increase(postgresql_db_size_bytes[1d])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Transactions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(postgresql_commits_total[5m])",
     "legendFormat": "Commits"
    },
    {
     "expr": "rate(postgresql_rollbacks_total[5m])",
     "legendFormat": "Rollbacks"
    }
   ]
  },
  {
   "title": "PostgreSQL - Index Scans (per second)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(postgresql_index_scans_total[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Database Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "sum by (instance) (postgresql_backends)\n/\nsum by (instance) (postgresql_connection_max)\n* 100",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}