{
 "title": "Payment System - Production Overview",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "environment",
    "label": "Environment",
    "query": {
     "query": "label_values(http_server_request_duration_seconds_count,deployment_environment)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "HTTP 4xx Rate",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\n  sum(rate(http_server_request_duration_seconds_count{http_response_status_code=~\"4..\", deployment_environment=~\"$environment\"}[5m]))\n  /\n  sum(rate(http_server_request_duration_seconds_count{deployment_environment=~\"$environment\"}[5m]))\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP Error Rate (%)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent (0-100)" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\n  sum(rate(http_server_request_duration_seconds_count{http_response_status_code=~\"5..\", deployment_environment=~\"$environment\"}[5m]))\n  /\n  sum(rate(http_server_request_duration_seconds_count{deployment_environment=~\"$environment\"}[5m]))\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_request_duration_seconds_count{deployment_environment=~\"$environment\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP Latência P99",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(\n  0.99,\n  sum(rate(http_server_request_duration_seconds_bucket{deployment_environment=~\"$environment\"}[5m])) by (le)\n) * 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP Latência P95",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(\n  0.95,\n  sum(rate(http_server_request_duration_seconds_bucket{deployment_environment=~\"$environment\"}[5m])) by (le)\n) * 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "UseCase Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent (0-100)" } },
   "targets": [
    {
     "expr": "(\n  sum(rate(application_usecase_errors_total{deployment_environment=~\"$environment\"}[5m])) by (usecase)\n  /\n  sum(rate(application_usecase_invocations_total{deployment_environment=~\"$environment\"}[5m])) by (usecase)\n) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "UseCase Latência P95",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(\n  0.95,\n  sum(rate(application_usecase_duration_bucket{deployment_environment=~\"$environment\"}[5m])) \n  by (le, usecase)\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Volume Financeiro por Minuto",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "BRL (R$)" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(transaction_amount_total{deployment_environment=~\"$environment\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "UseCase Throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "req/s" } },
   "targets": [
    {
     "expr": "sum(rate(application_usecase_invocations_total{deployment_environment=~\"$environment\"}[1m])) by (usecase)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latência por Endpoint (P95)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(\n  0.95,\n  sum(\n    rate(http_server_request_duration_seconds_bucket{deployment_environment=~\"$environment\"}[5m])\n  ) by (le, http_route, http_request_method)\n) * 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Processado Última Hora",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "BRL (R$)" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(transaction_amount_total{deployment_environment=~\"$environment\"}[1h]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Heap total (%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(\n  sum(jvm_memory_used_bytes{area=\"heap\", deployment_environment=~\"$environment\"})\n  /\n  sum(jvm_memory_max_bytes{area=\"heap\", deployment_environment=~\"$environment\"})\n) * 100",
     "legendFormat": "Heap used"
    }
   ]
  },
  {
   "title": "Requests por Status",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "req/s" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_request_duration_seconds_count{deployment_environment=~\"$environment\"}[5m])) by (http_response_status_code)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Hikari Connection Timeouts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "targets": [
    {
     "expr": "rate(hikaricp_connections_timeout_total{deployment_environment=~\"$environment\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Hikari Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (pool) (hikaricp_connections_active{deployment_environment=~\"$environment\"})",
     "legendFormat": "Active - {{pool}}"
    },
    {
     "expr": "sum by (pool) (hikaricp_connections_idle{deployment_environment=~\"$environment\"})",
     "legendFormat": "Idle - {{pool}}"
    },
    {
     "expr": "sum by (pool) (hikaricp_connections_max{deployment_environment=~\"$environment\"})",
     "legendFormat": "Max - {{pool}}"
    },
    {
     "expr": "sum by (pool) (hikaricp_connections_pending{deployment_environment=~\"$environment\"})",
     "legendFormat": "Pending - {{pool}}"
    },
    {
     "expr": "sum by (pool) (hikaricp_connections_min{deployment_environment=~\"$environment\"})",
     "legendFormat": "Min - {{pool}}"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "expr": "process_cpu_usage * 100", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Memory Non-Heap Usage (Metaspace)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{id=\"Metaspace\", deployment_environment=~\"$environment\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GC Pause Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "rate(jvm_gc_pause_milliseconds_sum{deployment_environment=~\"$environment\"}[5m])\n/\nrate(jvm_gc_pause_milliseconds_count{deployment_environment=~\"$environment\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Heap Usage by Memory Region",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (id) (\n  jvm_memory_used_bytes{area=\"heap\", deployment_environment=~\"$environment\"}\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GC Frequency (Young vs Old)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum by (gc) (\n  rate(jvm_gc_pause_milliseconds_count{deployment_environment=~\"$environment\"}[5m])\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Application Uptime",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 80 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_uptime_milliseconds{deployment_environment=~\"$environment\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "JVM Threads",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 80 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "jvm_threads_live{deployment_environment=~\"$environment\"}",
     "legendFormat": "Live Threads"
    },
    {
     "expr": "jvm_threads_daemon{deployment_environment=~\"$environment\"}",
     "legendFormat": "Daemon Threads"
    },
    {
     "expr": "jvm_threads_peak{deployment_environment=~\"$environment\"}",
     "legendFormat": "Peak Threads"
    },
    {
     "expr": "sum by (state) (\n  jvm_threads_states{deployment_environment=~\"$environment\"}\n)",
     "legendFormat": "{{state}}"
    }
   ]
  }
 ]
}