plugins {
    id 'java-library'
    id 'java-conventions'
}

group = 'com.payment.system.domain'

dependencies {
    implementation 'net.datafaker:datafaker:2.0.1'
    implementation 'com.github.f4b6a3:ulid-creator:5.2.3'
}

configurations {
    testClasses {
        extendsFrom(testImplementation)
    }
}

tasks.register('testJar', Jar) {
    archiveClassifier.set('test')
    from sourceSets.test.output
}

artifacts {
    testClasses testJar
}